packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@sentry/cli': set this to true or false
  esbuild: true
trustLockfile: true
verifyDepsBeforeRun: false
minimumReleaseAgeExclude:
  - '@nestjs/drizzle@0.0.1'
